recipes = {
    "Pasta Primavera": {"ingredients": ["pasta", "bell peppers", "tomatoes", "cheese"], "vegan": False},
    "Chicken Curry": {"ingredients": ["chicken", "curry powder", "onions", "coconut milk"], "vegan": False},
    "Vegetable Stir Fry": {"ingredients": ["broccoli", "carrots", "soy sauce", "garlic"], "vegan": True},
    "Guacamole": {"ingredients": ["avocado", "lime", "onions", "tomatoes"], "vegan": True},
    "Pasta Carbonara": {"ingredients": ["pasta", "chicken", "cheese", "eggs"], "vegan": False},
    "Beef Tacos": {"ingredients": ["ground beef", "taco seasoning", "lettuce", "cheese", "tortillas"], "vegan": False},
    "Margherita Pizza": {"ingredients": ["pizza dough", "tomato sauce", "mozzarella", "basil"], "vegan": False},
    "Shakshuka": {"ingredients": ["eggs", "tomatoes", "onions", "garlic", "bell peppers"], "vegan": False},
    "Caprese Salad": {"ingredients": ["tomatoes", "mozzarella", "basil", "olive oil"], "vegan": False},
    "Pad Thai": {"ingredients": ["rice noodles", "peanuts", "soy sauce", "bean sprouts", "lime"], "vegan": True},
    "Lentil Soup": {"ingredients": ["lentils", "carrots", "onions", "celery", "garlic"], "vegan": True},
    "Greek Salad": {"ingredients": ["cucumbers", "tomatoes", "feta", "olives", "red onions"], "vegan": False},
    "Fish Tacos": {"ingredients": ["fish fillets", "tortillas", "cabbage", "lime", "sour cream"], "vegan": False},
    "Vegetarian Chili": {"ingredients": ["beans", "tomatoes", "onions", "bell peppers", "chili powder"], "vegan": True},
    "Spaghetti Bolognese": {"ingredients": ["spaghetti", "ground beef", "tomato sauce", "onions", "garlic"], "vegan": False},
    "Egg Fried Rice": {"ingredients": ["rice", "eggs", "soy sauce", "peas", "carrots"], "vegan": False},
    "Pumpkin Soup": {"ingredients": ["pumpkin", "onions", "garlic", "cream", "vegetable stock"], "vegan": True},
    "Cobb Salad": {"ingredients": ["lettuce", "chicken", "bacon", "eggs", "avocado", "blue cheese"], "vegan": False},
    "Teriyaki Chicken": {"ingredients": ["chicken", "soy sauce", "brown sugar", "ginger", "garlic"], "vegan": False},
    "Vegetable Curry": {"ingredients": ["potatoes", "carrots", "coconut milk", "curry powder", "onions"], "vegan": True},
    "Caesar Salad": {"ingredients": ["romaine lettuce", "parmesan", "croutons", "caesar dressing"], "vegan": False},
    "Tomato Basil Soup": {"ingredients": ["tomatoes", "basil", "onions", "cream", "vegetable stock"], "vegan": True},
    "Fajitas": {"ingredients": ["chicken", "bell peppers", "onions", "tortillas", "fajita seasoning"], "vegan": False},
    "Ratatouille": {"ingredients": ["zucchini", "eggplant", "tomatoes", "onions", "bell peppers"], "vegan": True},
    "Chickpea Salad": {"ingredients": ["chickpeas", "cucumbers", "tomatoes", "parsley", "lemon juice"], "vegan": True},
    "Black Bean Burgers": {"ingredients": ["black beans", "breadcrumbs", "onions", "garlic", "spices"], "vegan": True},
    "Tofu Scramble": {"ingredients": ["tofu", "turmeric", "onions", "spinach", "bell peppers"], "vegan": True},
    "Stuffed Bell Peppers": {"ingredients": ["bell peppers", "rice", "black beans", "corn", "tomato sauce"], "vegan": True},
    "Vegan Pancakes": {"ingredients": ["flour", "almond milk", "baking powder", "maple syrup", "vanilla"], "vegan": True},
}

