recipes = {
    "Pasta Primavera": ["pasta", "bell peppers", "tomatoes", "cheese"],
    "Chicken Curry": ["chicken", "curry powder", "onions", "coconut milk"],
    "Vegetable Stir Fry": ["broccoli", "carrots", "soy sauce", "garlic"],
    "Guacamole": ["avocado", "lime", "onions", "tomatoes"],
    "Pasta Carbonara": ["pasta", "chicken", "cheese", "eggs"],
    "Beef Tacos": ["ground beef", "taco seasoning", "lettuce", "cheese", "tortillas"],
    "Margherita Pizza": ["pizza dough", "tomato sauce", "mozzarella", "basil"],
    "Shakshuka": ["eggs", "tomatoes", "onions", "garlic", "bell peppers"],
    "Caprese Salad": ["tomatoes", "mozzarella", "basil", "olive oil"],
    "Pad Thai": ["rice noodles", "peanuts", "soy sauce", "bean sprouts", "lime"],
    "Chicken Alfredo": ["pasta", "chicken", "parmesan", "cream", "garlic"],
    "Lentil Soup": ["lentils", "carrots", "onions", "celery", "garlic"],
    "Greek Salad": ["cucumbers", "tomatoes", "feta", "olives", "red onions"],
    "Fish Tacos": ["fish fillets", "tortillas", "cabbage", "lime", "sour cream"],
    "Vegetarian Chili": ["beans", "tomatoes", "onions", "bell peppers", "chili powder"],
    "Spaghetti Bolognese": ["spaghetti", "ground beef", "tomato sauce", "onions", "garlic"],
    "Egg Fried Rice": ["rice", "eggs", "soy sauce", "peas", "carrots"],
    "Pumpkin Soup": ["pumpkin", "onions", "garlic", "cream", "vegetable stock"],
    "Cobb Salad": ["lettuce", "chicken", "bacon", "eggs", "avocado", "blue cheese"],
    "Teriyaki Chicken": ["chicken", "soy sauce", "brown sugar", "ginger", "garlic"],
    "Vegetable Curry": ["potatoes", "carrots", "coconut milk", "curry powder", "onions"],
    "Caesar Salad": ["romaine lettuce", "parmesan", "croutons", "caesar dressing"],
    "Tomato Basil Soup": ["tomatoes", "basil", "onions", "cream", "vegetable stock"],
    "Fajitas": ["chicken", "bell peppers", "onions", "tortillas", "fajita seasoning"],
    "Ratatouille": ["zucchini", "eggplant", "tomatoes", "onions", "bell peppers"],
}
